### Index method
GET http://localhost:3000/api/jokes

### Successfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
  "category_id": 1,
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand"
}

### Unsuccessfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand"
}

### Show joke id: 1
GET http://localhost:3000/api/jokes/1

### Unsuccessfully show joke id: 1000
GET http://localhost:3000/api/jokes/1000

### Successfully update joke 1
PUT http://localhost:3000/api/jokes/1
Content-Type: application/json

{
  "category_id": 2,
  "body": "A programming joke"
}

### Successfully delete joke with id 1
DELETE http://localhost:3000/api/jokes/1

### Unsuccessfully delete joke with id 1000
DELETE http://localhost:3000/api/jokes/1000 

### Random joke
GET http://localhost:3000/api/jokes/random?category=puns

### Unsuccessful random joke
GET http://localhost:3000/api/jokes/random?category=hfjdkfhks


### Create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "username": "victor_3",
  "email": "victor3@test.com",
  "password": "password3",
  "password_confirmation": "password3"
}

### Sign in with correct details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "victor3@test.com",
  "password": "password3"
}

### Sign in with incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "victor3@test.com",
  "password": "whatever"
}